#!/usr/bin/perl -T

#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use warnings;
use esmith::ConfigDB;
use esmith::util;

our $db = esmith::ConfigDB->open or
    die "Couldn't open configuration database (permissions problems?)";

my $strength = $db->get_prop('passwordstrength', 'Users');
my $password = <>;
chomp $password;

my $reason = esmith::util::validatePassword($password, $strength);

exit 0 if (lc($reason) eq "ok");
exit 1;
