#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);


templates2events("/etc/samba/smb.conf", qw(
    nethserver-samba-update
    nethserver-samba-save
    ibay-create
    ibay-delete
    ibay-modify
    network-delete
    network-create
));

my $event;

event_actions('nethserver-samba-update',
	      "initialize-default-databases" => '00',
	      "nethserver-samba-conf" => '20',
	      "nethserver-samba-sam-conf" => '95',
	      "nethserver-samba-user-create" => '96',
	      "nethserver-samba-group-create" => '97'
    );

event_actions('group-create', 
	      "nethserver-samba-group-create" => "30"
);

# All of these events require smbd to reload the smb.conf file:
event_actions($event,
	      "nethserver-samba-smbd-adjust" => '95'
) foreach my $event (qw(
    group-create
    group-delete
    group-modify
    ibay-create
    ibay-delete
    ibay-modify
    network-create
    network-delete
    printer-create
    printer-delete
));

event_actions('user-create',
	      "nethserver-samba-user-create" => '20',
	      "nethserver-samba-profile-create" => '25',
	      "nethserver-samba-user-modify" => '30',
);

event_actions('user-delete',
	      "nethserver-samba-profile-delete" => '20',
	      "nethserver-samba-smbd-adjust" => '95',
);

event_actions('user-modify',
	      "nethserver-samba-user-modify" => '30',
);

event_actions('user-lock',
	      "nethserver-samba-user-modify" => '30',
	      "nethserver-samba-smbd-adjust" => '95',
);

event_actions('user-unlock',
	      "nethserver-samba-user-modify" => '30',
	      "nethserver-samba-smbd-adjust" => '95',
);

event_actions("delete_printer_tdb",
	      'printer-delete' => '15',
);

event_actions("nethserver-samba-machine-create",
	      "nethserver-samba-machine-create" => '10',
);

event_actions('password-modify',
	      "nethserver-samba-password-modify" => '40',
);

# event nethserver-samba-save
safe_symlink("restart", "root/etc/e-smith/events/nethserver-samba-save/services2adjust/$daemon") 
    foreach my $daemon (qw(smb nmb winbind));

	     
#
# restart daemons on update of required packages :
#
foreach my $daemon (qw(nmb smb winbind)) {
    foreach my $pkg (qw(base directory samba)) {
	safe_symlink("restart", 
		     "root/etc/e-smith/events/nethserver-$pkg-update/services2adjust/$daemon")
    }	
}


