#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

my $panel = "manager";
panel_link("workgroup", $panel);

foreach (qw(samba/smb.conf samba/smbusers))
{
    templates2events("/etc/$_", qw(
	console-save
	bootstrap-console-save
	ibay-create
	ibay-delete
	ibay-modify
	ibay-modify-servers
	network-delete
	network-create
	post-install
	post-upgrade
	workgroup-update
	));
}

foreach my $file (qw(
	/etc/pam.d/samba
	))
{
    templates2events($file, qw(console-save bootstrap-console-save));
}

my $event = "console-save";

$event = "bootstrap-console-save";
event_link("update-domain-group-maps", $event, "56");

$event = "group-create";
event_link("update-domain-group-maps", $event, "56");
safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/smb");

$event = "group-delete";
event_link("update-domain-group-maps", $event, "14");
safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/smb");

$event = "group-modify";
event_link("update-domain-group-maps", $event, "56");
safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/smb");

$event = "ibay-create";
safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/smb");

$event = "ibay-delete";
safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/smb");

$event = "ibay-modify";
safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/smb");

$event = "ibay-modify-servers";
safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/smb");

$event = "network-create";
safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/smb");

$event = "network-delete";
safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/smb");

$event = "post-install";

$event = "post-upgrade";
event_link("user-create-profiledir", $event, "20");

$event = "user-create";
event_link("user-create-profiledir", $event, "20");
safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/smb");

$event = "user-delete";
event_link("user-delete-profiledir", $event, "20");
safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/smb");

$event = "user-modify";
safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/smb");

$event = "workgroup-update";
event_link("update-domain-group-maps", $event, "56");
safe_symlink("sigterm", "root/etc/e-smith/events/$event/services2adjust/dhcpd");
safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/smb");
safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/nmb");
safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/winbind");
templates2events("/etc/krb5.conf", $event);

$event = "printer-create";
safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/smb");

$event = "printer-delete";
event_link("delete_printer_tdb", $event, 15);
safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/smb");

$event = "machine-account-create";
event_link("create-machine-account", $event, "10");

$event = "nethserver-samba-update";
templates2events("/etc/samba/smb.conf", $event);
templates2events("/etc/krb5.conf", $event);
safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/nmb");
safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/smb");
safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/winbind");


$event = "nethserver-base-update";
safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/nmb");
safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/smb");
safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/winbind");
