#!/usr/bin/perl -w

#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use esmith::Build::CreateLinks qw(:all);
use File::Path;


#
# nethserver-samba-update event (smb.conf template expanded above)
#
event_templates('nethserver-samba-update', qw(
    /etc/samba/smb.conf
    /etc/hosts
));

event_actions('nethserver-samba-update', qw(
	      initialize-default-databases 00
	      nethserver-samba-conf 20
));

event_services('nethserver-samba-update', qw(
   smb restart
   nmb restart
));


#--------------------------------------------------
# actions for trusted-networks-modify event
#--------------------------------------------------
event_templates('trusted-networks-modify', qw(
    /etc/samba/smb.conf
));

event_services('trusted-networks-modify', qw(
   smb restart
   nmb restart
));

#--------------------------------------------------
# actions for post-restore-config event
#--------------------------------------------------

event_actions('post-restore-config', qw(
	      nethserver-samba-restore-tdb 40
));

#--------------------------------------------------
# actions for pre-backup-config event
#--------------------------------------------------

event_actions('pre-backup-config', qw(
	      nethserver-samba-backup-tdb 40
));

#
# migration-import event (refs #1657)
#
event_actions('migration-import', qw(
    nethserver-samba-migrate-ibays  40
));

event_services('migration-import', qw(
    smb restart
    nmb restart
));

#
# Event hostname-modify
#
event_actions('hostname-modify', qw(
      nethserver-samba-setsidfromdb 40
));

