#!/usr/bin/perl

#
# Copyright (C) 2019 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use warnings;
use strict;
use JSON;
use esmith::ConfigDB;
use NethServer::ApiTools;

require '/usr/libexec/nethserver/api/lib/helper_functions.pl';

my $ret;

my $db = esmith::ConfigDB->open_ro();
$ret->{'Workgroup'} = $db->get_prop('sssd', 'Workgroup') || 'WORKGROUP';
foreach (qw(ShareAdmStatus HomeAdmStatus InheritOwner)) {
    $ret->{$_} = $db->get_prop('smb', $_);
}
my $provider = $db->get_prop('sssd', 'Provider') || '';
if ($provider eq 'ad') {
    $ret->{'WorkgroupEditable'} = JSON::false;
} else {
    $ret->{'WorkgroupEditable'} = JSON::true;
}
print encode_json($ret);
