#!/usr/bin/perl -w

use esmith::util;

system("smbpasswd", "-w", "password") == 0
   or die ("Can't save ldap password in sambapasswd");

my $sid = `/usr/bin/net getlocalsid 2>/dev/null | /bin/cut -d':' -f2`;
$sid =~ s/^\s+//;
$sid =~ s/\s+$//;

die("Can't read samba local sid") unless ($sid ne "");

# add admin user to samba with null password
system('/bin/echo -e "\n\n" | /usr/bin/pdbedit -t -U '.$sid.'-500 -u admin -a') == 0
   or die ("Can't set admin user as Domain Admin");

system("/usr/bin/smbpasswd", "-d", "admin") == 0
   or die "Error running /usr/bin/smbpasswd command to lock admin account";

