#!/usr/bin/perl

#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;

use NethServer::Migrate 'migrateDir';
use File::Basename;

my $event = shift;
my $sourceDir = shift;
my $errors = 0;

foreach ($sourceDir, glob $sourceDir . '/home/e-smith/files/samba/{profiles,printers,netlogon}') {
    if( ! -d $_) {
	die("[ERROR] could not find source directory $sourceDir\n");
    } 
}

#
# migrate roaming profile directories:
#
for my $srcProfileDir (glob $sourceDir . '/home/e-smith/files/samba/profiles/*') {
    my $dirName = basename($srcProfileDir);

    my $dstProfileDir = '/var/lib/nethserver/profile/' . $dirName;

    if( -d $dstProfileDir) {
	migrateDir($srcProfileDir, $dstProfileDir) || $errors++;
    } else {
	print "[WARNING] $dirName: destination profile does not exist. Skipped.\n";
    }
}


#
# migrate printer drivers and netlogon shares
#
migrateDir($sourceDir . '/home/e-smith/files/samba/printers', '/var/lib/nethserver/print_driver') || $errors ++;
migrateDir($sourceDir . '/home/e-smith/files/samba/netlogon', '/var/lib/nethserver/netlogon') || $errors ++;


if($errors > 0) {
    warn "[WARNING] $errors error(s) occurred in nethserver-samba-data action\n";
    exit(1);
}

# action ends:
exit(0);
