#!/usr/bin/perl

#
# NethServer Samba
#
#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use esmith::AccountsDB;

my $event = shift || die("Missing event argument!");
my $user= shift || die("No user specified");
my $accountsDb = esmith::AccountsDB->open() || die("Could not open accounts database");
my $record = $accountsDb->get($user) || die("User `$user` not found in accounts database");
my $exitCode = 0;
my $net = '/usr/bin/net';
my $smbpasswd = '/usr/bin/smbpasswd';

if($record->prop('type') ne 'user') {
    die("`$user` is not a user record");
}

# Update SAM db to reflect the "active" state of the user account:
{
    my $isEnabled;
    
    if($record->prop('__state') eq 'active' 
       && $record->prop('Samba') eq 'enabled') {
	$isEnabled = 1;
    } else {
	$isEnabled = 0;
    }
    
    if(system($net, qw(sam set disabled), $user, $isEnabled ? 'yes' : 'no') != 0) {
	warn "Failed to change enabled state of SAM user `$user`";
	$exitCode ++;
    }
}

# Update SAM user fullname and comment
{
    my $fullName = join(' ', $record->prop('FirstName'), $record->prop('LastName'));
    foreach my $attribute (qw(fullname comment)) {
	system($net, 'sam', 'set', $attribute, $user, $fullName);
	if($? != 0) {
	    warn "Failed to change full name of SAM user `$user`";
	    $exitCode ++;
	}
    }
} 

exit($exitCode == 0 ? 0 : 1);

