#!/usr/bin/perl -w
#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# copyright (C) 2001 Mitel Networks Corporation
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

#
# On unix account for samba machine see:
# http://www.samba.org/samba/docs/man/Samba-HOWTO-Collection/domain-member.html#machine-trust-accounts
#

package esmith;

use strict;
use Errno;
use esmith::ConfigDB;
use esmith::AccountsDB;
use esmith::util;

my $a = esmith::AccountsDB->open || die "Couldn't open accounts db\n";

my $event = $ARGV [0];
my $machineName = $ARGV [1];

# Machine account names MUST end with dollar sign '$':
die "machine name $machineName is not a valid machine account name"
	unless ( $machineName =~ /\$$/ );

my $m = $a->get($machineName);
if ($m) {
    my $type = $m->prop('type');
    die "$machineName is not a machine account" 
	unless ($type eq "machine");
} else {
    # Create the machine record in AccountsDB
    $a->new_record($machineName, {type => "machine"});
}

# We really, really need to be root to run "passwd -l"
esmith::util::setRealToEffective();

system(
	"/usr/sbin/luseradd",
	"-c", "Samba machine $machineName account",
	"-M",
	"-d", "/noexistingpath",
	"-s", "/bin/false",
	"$machineName"
    ) == 0 or die "Failed to create account $machineName.\n";

system("/usr/sbin/lusermod", "-L", "$machineName") == 0
    or warn("Could not lock password for $machineName\n");

exit (0);
