#!/usr/bin/perl

#
# NethServer Samba
#
# Load the samba schema in LDAP configuration database. 
# Exit silently if the schema is already loaded.
#
#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#


use strict;

use NethServer::Directory;
use NethServer::Service;
use esmith::event;

my $ldap = NethServer::Directory->new();
my $internalSuffix = NethServer::Directory::getInternalSuffix();
my $exitCode = 0;

$ldap->loadLdifSchema('samba', '/etc/openldap/schema/samba.ldif') || die("Could not load the samba LDIF schema");

{ # BEGIN LDAP

    my $password = NethServer::Directory::getUserPassword('samba', 0);

    #
    # Store the LDAP password in samba secrets.tdb database, for both
    # ldap and idmap backends:
    #
    qx(/usr/bin/smbpasswd -w '$password');
    qx(/usr/bin/net idmap secret '*' '$password');

    my @entries = (
	[ 'ou=Idmap,' . $internalSuffix,
	  attrs => [
	      objectClass => ['top', 'organizationalUnit'],
	      ou => 'Idmap',
	  ] ],       	
	);

    foreach(@entries) {
	my $message = $ldap->merge(@{$_});
	if($message->is_error()) {
	    warn 'error merging ' . @{$_}[0];
	    $exitCode ++;
	}
    }

    #
    # LDAP ACL setup for samba service account: (ex nethserver-samba-aclsetup)
    # 

    my $sambaWho = qq(by dn.exact="cn=samba,$internalSuffix" peername.ip="127.0.0.1");

    # Configure the samba service account to access samba LDAP DB:
    $ldap->configServiceAccount('samba');

    # Grant write permission to samba and make sambaNTPassword
    # readable only by samba user:
    $ldap->enforceAccessDirective($sambaWho . ' write by self write by * none', 'sambaNTPassword') || $exitCode ++;
    $ldap->enforceAccessDirective($sambaWho . ' write', '*') ||  $exitCode ++;

} # END LDAP

NethServer::Service::manage_add('nethserver-samba',
				'smb',
				'nmb',
				'winbind');

# Enable acl and user_xattr on / filesystem
my $confdb = esmith::ConfigDB->open;
my $fstab = $confdb->get('fstab') or return "";

my $prop = $fstab->prop('/') || 'defaults';
$prop .= ",acl" unless ($prop =~ /acl/);
$prop .= ",user_xattr" unless ($prop =~ /user_xattr/);
$fstab->set_prop('/',$prop);

if( ! esmith::event::event_signal('fstab-update')) {
    warn "[WARNING] Errors during fstab-update event";
    $exitCode ++;
}


exit($exitCode);
