#!/usr/bin/perl -w
##
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# copyright (C) 2001-2005 Mitel Networks Corporation
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#
package esmith;

use strict;
use Errno;
use esmith::util;

use esmith::AccountsDB;

my $adb = esmith::AccountsDB->open_ro();
my $event = $ARGV[0];
my @users = map { $_->key } $adb->users;
my @newusers;

if($ARGV[1]) {
    @newusers = $ARGV[1];
} else {
    @newusers = @users;
}

foreach my $user ( @newusers )
{
    die "$user is not a user account\n"
        unless ( grep /^$user$/, @users );

    # Windows 7 and above each have a new user profile type defined by the .Vx file extension.
    my @dirs = (
	'/var/lib/nethserver/profile/' . $user,
	'/var/lib/nethserver/profile/' . $user . '.V2', # Windows 7
	'/var/lib/nethserver/profile/' . $user . '.V3', # Windows 8
	'/var/lib/nethserver/profile/' . $user . '.V4', # Windows 8.1
	'/var/lib/nethserver/profile/' . $user . '.V5' # Windows 10
	);
    
    foreach my $dir (@dirs)  {
	if( ! -d $dir) {
	    mkdir $dir;
	    esmith::util::chownFile($user, $user, $dir) || 
		warn "Couldn't change ownership of $dir\n";
	} 
	chmod 0700, $dir;  # Remove setgid bit
    }
}

exit (0);
