#!/usr/bin/perl

#
# NethServer - Samba smbd adjust action
#
# Asks smbd to reload configuration and close the given user's
# connections.
#
#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use esmith::AccountsDB;

my $errors = 0;
my ($event, $user) = @ARGV;

# validate the user argument before proceed:
if(defined $user) {
    my $accountsDb = esmith::AccountsDB->open_ro() || die('Could not open AccountsDB');    
    my $accountType = $accountsDb->get_prop($user, 'type');
    if($accountType ne 'user' 
       && $accountType ne 'user-deleted') {
	# See below: smbd reload configuration
	undef $user; 
    }
}

# obtain a list of smbd process IDs:
open(my $ps, '-|', "/bin/ps --no-heading -C smbd -o user,pid,ppid");

while( ! eof($ps)) {
    my $line = <$ps>;
    chomp($line);

    my ($owner, $pid, $ppid) = split(/\s+/, $line);

    if($ppid eq '1') {
	# ask the smbd root process to reload configuration
	kill 1, $pid;
    } elsif(defined $user && $owner eq $user) {
	# terminate user's process, closing active connections
	kill 15, $pid;
    }
}


exit($errors > 0 ? 1 : 0);
