#!/usr/bin/perl

#
# NethServer Samba
#
#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;

my $event = shift;
my $user= shift;
my $file = shift;

if(!$user) {
    die("Missing user argument!");
}

if(!$file) {
    die("Missing file argument!");
}

# Check if user is in SAM database
qx(/usr/bin/net sam show $user >/dev/null 2>&1);
if($? != 0) {
    die("User $user not found in SAM database");
}

open(PWD, '<', $file) or die("Error retrieving password token");
my $password = <PWD>;
chomp($password);
close PWD;

if($password eq "") {
    die("Error: samba empty password is not allowed");
}

open(SMBPASSWD, '|-', "/usr/bin/smbpasswd -s '$user'") or die("Cannot open pipe to smbpasswd");
print SMBPASSWD "$password\n$password";
close SMBPASSWD;

exit $?;
