#!/usr/bin/perl

use strict;

use NethServer::Directory;
use NethServer::Service;

#
# Refs #1137. Skip acl setup, if samba is not enabled
#
if( ! NethServer::Service::is_enabled('smb')) {
    warn "smb service is currently not enabled, skipping ldap ACL setup.\n";
    exit 0;
}


my $ldap = NethServer::Directory::connect();
my $internalSuffix = NethServer::Directory::getInternalSuffix();
my $exitCode = 0;

#use Data::Dumper;

#
# Modify Bdb ACL to grant write permission to samba 
#
my $accessSearch = $ldap->search(
    base => "cn=config",
    filter => "(&(olcSuffix=$internalSuffix)(objectClass=olcBdbConfig))",
    sizelimit => 1,
    scope => 'one'
    );

if($accessSearch->is_error()) {	
    warn "Cannot find `$internalSuffix` subtree";
    $exitCode ++;
} else {
    my $aclEntry = $accessSearch->pop_entry();

    if($aclEntry) {
	my $sambaWho = qq( by dn.exact="cn=samba,$internalSuffix" peername.ip="127.0.0.1" write );
	my @olcAccess = $aclEntry->get_value('olcAccess');

	foreach(@olcAccess) {
	    s/ manage/ manage $sambaWho/ if (m/to \*/s && ! m/\Q$sambaWho\E/);
	}

	# print Dumper([@olcAccess]);	    
	my $message = $ldap->modify(
	    $aclEntry->dn(),
	    replace => [
		olcAccess => [@olcAccess]
	    ]);

	if($message->is_error()) {    	
	    warn 'modify';
	    $exitCode ++;
	}
    } 
}

exit ($exitCode == 0) ? 0 : 1;
