#!/usr/bin/perl

#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;

use NethServer::Directory;
use NethServer::Service;

my $ldap = NethServer::Directory->new();
my $internalSuffix = NethServer::Directory::getInternalSuffix();
my $sambaWho = qq(by dn.exact="cn=samba,$internalSuffix" peername.ip="127.0.0.1");
my $errors = 0;


# Configure the samba service account to access samba LDAP DB:
$ldap->configServiceAccount('samba');

# Grant write permission to samba and make sambaNTPassword readable
# only by samba user:
if( ! $ldap->enforceAccessDirective($sambaWho . ' write by self write by * none', 'sambaNTPassword')) {
    $errors ++;
}

if( ! $ldap->enforceAccessDirective($sambaWho . ' write', '*')) {
    $errors ++;
}

exit ($errors == 0 ? 0 : 1);
