#!/usr/bin/perl

#
# NethServer Samba
#
# Load the samba schema in LDAP configuration database. 
# Exit silently if the schema is already loaded.
#
#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;

use NethServer::Password;
use esmith::event;
use esmith::ConfigDB;

my $errors = 0;
my $confdb = esmith::ConfigDB->open() || die("Could not open ConfigDB");

# Enable acl and user_xattr on / filesystem
my $fstab = $confdb->get('fstab') or return "";

my $prop = $fstab->prop('/') || 'defaults';
$prop .= ",acl" unless ($prop =~ /acl/);
$prop .= ",user_xattr" unless ($prop =~ /user_xattr/);
$fstab->set_prop('/',$prop);

if( ! esmith::event::event_signal('fstab-update')) {
    warn "[ERROR] Errors during fstab-update event";
    $errors ++;
}

exit($errors == 0 ? 0 : 1);
