#! /usr/bin/perl -w
#
# Copyright (C) 2017 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use esmith::AccountsDB;
use File::stat;

# Migrate ibays from NS 6: map locals group to "Domain Users"
my $adb = esmith::AccountsDB->open();
my $gid = getgrnam("domain users");

# Execute only if the server is joined to AD
if ($gid) {
    my $gname = getgrgid($gid);

    foreach my $ibay ($adb->ibays) {
        my $path = "/var/lib/nethserver/ibay/".$ibay->key;
        my $owning_group = $ibay->prop('OwningGroup') || '';
        if ($owning_group eq 'locals' && -e $path) {
            print "[NOTICE] Fixing owning group for shared folder '".$ibay->key."'\n";

            # recursively change group
            my $stat = stat($path);
            my $current_gid = $stat->gid;
            system("chown -R --from=:$current_gid :$gid $path");

            $ibay->set_prop('OwningGroup',$gname);
        }
    }
}
