#!/usr/bin/perl -w
#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# copyright (C) 1999-2005 Mitel Networks Corporation
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#
package esmith;

use strict;
use Errno;
use File::Path;

use esmith::AccountsDB;
my $adb = esmith::AccountsDB->open_ro();

my $event = $ARGV [0];
my $account = $ARGV [1];

$a = $adb->get($account) || undef;
unless ( defined $a && $a->prop('type') eq "user-deleted" )
{
    warn "$account is not a user account\n";
    exit (0);
}

my @dirs = (
    '/var/lib/nethserver/profile/' . $account, 
    '/var/lib/nethserver/profile/' . $account. '.V2',
    '/var/lib/nethserver/profile/' . $account. '.V3',
    '/var/lib/nethserver/profile/' . $account. '.V4',
    '/var/lib/nethserver/profile/' . $account. '.V5'
); 

foreach (@dirs) {
 
    next unless -d $_;
    rmtree( $_ ) || warn "Couldn't remove user `$account` profile directory $_\n";

}

exit (0);
