#!/usr/bin/perl

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use esmith::AccountsDB;
use esmith::ConfigDB;

my $cdb = esmith::ConfigDB->open();
my $adb = esmith::AccountsDB->open();

my $domain = $cdb->get('DomainName')->prop('type');
foreach my $ibay ($adb->ibays) {
    my $aclRead = $ibay->prop('AclRead') || '';
    my $aclWrite = $ibay->prop('AclWrite') || '';
    my @acl_read;
    my @acl_write;
    foreach my $obj (split(',',$aclRead)) {
        if ($aclRead !~ /@/) {
             $obj = $obj.'@'.$domain
        }
        push(@acl_read,$obj);
    }
    foreach my $obj (split(',',$aclWrite)) {
        if ($aclWrite !~ /@/) {
             $obj = $obj.'@'.$domain
        }
        push(@acl_write,$obj);
    }
    $aclRead = join(',',@acl_read);
    $aclWrite = join(',',@acl_write);
    $ibay->set_prop('AclRead',$aclRead);
    $ibay->set_prop('AclWrite',$aclWrite);

    my $OwningGroup = $ibay->prop('OwningGroup') || '';
    if($OwningGroup && $OwningGroup !~ /@/) {
        $ibay->set_prop('OwningGroup', $OwningGroup . '@'  . $domain);
    }
}
