#!/bin/bash

#
# Copyright (C) 2016 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

#
# Reset libwbclient to default Samba winbind library (#5647)
#

alternatives --set libwbclient.so.0.14-64 /usr/lib64/samba/wbclient/libwbclient.so.0.14 || :
echo "[NOTICE] $(alternatives --display libwbclient.so.0.14-64)"

# Fix duplicate SID for local machine and domain (required for ns6 upgraded systems)
if [[ $(net getdomainsid | grep -o -E ': S-[0-9-]+' | uniq | wc -l) == "1" ]]; then
    IFS=-
    read -a sid_parts <<<"$(net getdomainsid | grep -o -E ': S-[0-9-]+' | uniq)"
    sid_parts[0]="S"
    sid_parts[5]=$(echo ${sid_parts[5]} | rev)
    sid_parts[6]=$(echo ${sid_parts[6]} | rev)
    echo "[NOTICE] Fixing the local SID with ${sid_parts[*]}"
    net setlocalsid "${sid_parts[*]}"
fi
