#!/usr/bin/perl

#
# NethServer Samba
# Copyright (C) 2012 Nethesis srl
#

use strict;

my $event = shift;
my $user= shift;
my $file = shift;

if(!$user) {
    die("Missing user argument!");
}

if(!$file) {
    die("Missing file argument!");
}

# Check if user is in SAM database
qx(/usr/bin/net sam show $user >/dev/null 2>&1);
if($? != 0) {
    die("User $user not found in SAM database");
}

open(PWD, '<', $file) or die("Error retrieving password token");
my $password = <PWD>;
chomp($password);
close PWD;

if($password eq "") {
    die("Error: samba empty password is not allowed");
}

open(SMBPASSWD, '|-', "/usr/bin/smbpasswd -s '$user'") or die("Cannot open pipe to smbpasswd");
print SMBPASSWD "$password\n$password";
close SMBPASSWD;

exit $?;
