#!/usr/bin/perl

#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use esmith::AccountsDB;

my $event = shift;
my $sourceDir = shift;
my $esmithDbDir = '/home/e-smith/db';
my $errors = 0;

if( ! $event ) {
    die("Missing event argument!\n");
}

if( ! $sourceDir ) {
    die("Missing sourceDir argument!\n");
}

my $srcAccountsDb = esmith::AccountsDB->open_ro(join('', $sourceDir, $esmithDbDir, '/accounts')) or die("Could not open source accounts database in $sourceDir \n");
my $dstAccountsDb = esmith::AccountsDB->open('accounts') or die("Could not open destination account db\n");

foreach my $dstIbay ($dstAccountsDb->get_all_by_prop('type' => 'ibay'), $dstAccountsDb->get_all_by_prop('type' => 'ibay-migrate')) {
    my $ibayName = $dstIbay->key;
    my $srcIbay = $srcAccountsDb->get($ibayName);

    if( ! $srcIbay) {
	warn("[WARNING] ibay $ibayName is missing from source accounts DB. Skipped.\n");
	next;
    }

    my $recycle = $srcIbay->prop('RecycleBin') ||  'disabled';
    $dstIbay->set_prop('SmbRecycleBinStatus', $recycle);

    $dstIbay->merge_props(
	SmbStatus => 'enabled',
	SmbProfileType => 'migration',
	);

    #
    # Changes are applied by nethserver-ibays-commit action.
    #
}

if($errors > 0) {
    warn "[WARNING] $errors error(s) occurred in $0 action\n";
    exit(1);
}

# action ends:
exit(0);
