#!/usr/bin/perl -w
#----------------------------------------------------------------------
# copyright (C) 2001-2005 Mitel Networks Corporation
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 		
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 		
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
# 
#----------------------------------------------------------------------
package esmith;

use strict;
use Errno;
use esmith::util;

use esmith::AccountsDB;

my $adb = esmith::AccountsDB->open_ro();
my $event = $ARGV[0];
my @users = map { $_->key } $adb->users;
my @newusers;

if($ARGV[1]) {
    @newusers = $ARGV[1];
} else {
    @newusers = @users;
}

foreach my $user ( @newusers )
{
    die "$user is not a user account\n"
        unless ( grep /^$user$/, @users );

    # seems that .V2 profile dir is used by clients, starting from
    # Windows 7..
    my @dirs = (
	'/var/lib/nethserver/profile/' . $user,
	'/var/lib/nethserver/profile/' . $user . '.V2'
	);
    
    foreach my $dir (@dirs)  {
	if( ! -d $dir) {
	    mkdir $dir;
	    esmith::util::chownFile($user, $user, $dir) || 
		warn "Couldn't change ownership of $dir\n";
	} 
	chmod 0700, $dir;  # Remove setgid bit
    }
}

exit (0);
