#! /usr/bin/perl -w
#
# Copyright (C) 2013 Nethesis S.r.l.
#
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use NethServer::BackupConfig;

my $backup = new NethServer::BackupConfig();
$backup->set_log_file("/var/log/restore-config.log");

my $ret = 1;

if ( -f '/var/lib/nethserver/backup/acls.dump' ) {
    my $ret = system('cd /var/lib/nethserver/ibay; setfacl --restore /var/lib/nethserver/backup/acls.dump');
    if ($ret != 0) {
        $backup->bad_exit("Error during ibay restore",$ret);
    }
}


exit 0;
