#!/bin/sh

#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# copyright (C) 1999-2005 Mitel Networks Corporation
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

#------------------------------------------------------------
# Delete the Unix account and files for the ibay.
#------------------------------------------------------------

event=$1
ibay=$2

if [ -z "$ibay" ]; then
    echo ibay name argument missing
    exit 1
fi

/bin/rm -rf "/var/lib/nethserver/ibay/${ibay:-xxx}"

