#!/usr/bin/perl

#
# NethServer Samba
#
# Load the samba schema in LDAP configuration database. 
# Exit silently if the schema is already loaded.
#
#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#


use strict;

use NethServer::Directory;
use NethServer::Service;

my $ldap = NethServer::Directory::connect();
my $internalSuffix = NethServer::Directory::getInternalSuffix();
my $exitCode = 0;

$ldap->loadLdifSchema('samba', '/etc/openldap/schema/samba.ldif') || die("Could not load the samba LDIF schema");

{ # BEGIN LDAP

    my $password = NethServer::Directory::getUserPassword('samba', 0, $ldap);

    #
    # Store the password in samba secrets.tdb database:
    #
    qx(smbpasswd -w '$password');

    my @entries = (
	[ 'cn=samba,' . $internalSuffix,
	  attrs => [
	      objectClass => ['device', 'simpleSecurityObject'],
	      cn => 'samba',
	      userPassword => NethServer::Directory::getUserPassword('samba', 1, $ldap),
	      description => 'Samba ldapsam management account'
	  ] ],
	[ 'ou=Computers,' . $internalSuffix,
	  attrs => [
	      objectClass => ['top', 'organizationalUnit'],
	      ou => 'Computers',
	  ] ],       	
	[ 'ou=Idmap,' . $internalSuffix,
	  attrs => [
	      objectClass => ['top', 'organizationalUnit'],
	      ou => 'Idmap',
	  ] ],       	
	);

    foreach(@entries) {
	my $message = $ldap->merge(@{$_});
	if($message->is_error()) {
	    warn 'error merging ' . $_[0];
	    $exitCode ++;
	}
    }

} # END LDAP

NethServer::Service::manage_add('nethserver-samba',
				'smb',
				'nmb',
				'winbind');

exit($exitCode);
