#!/bin/bash

#
# Copyright (C) 2016 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

ibayName=${2:-xxx}
ibayPath=/var/lib/nethserver/ibay/${ibayName}
errors=0

if [[ ! -d "${ibayPath}" ]]; then
    echo "[ERROR] shared folder not found: ${ibayPath}"
    exit 1
fi

getfacl "${ibayPath}" | sed '/^[^#]/ s/x$/X/' | setfacl  -R --set-file=- "${ibayPath}"
if [[ $? != 0 ]]; then
    errors=1
fi

chown -R --reference="${ibayPath}" "${ibayPath}"
if [[ $? != 0 ]]; then
    errors=1
fi

exit  ${errors}