#!/bin/bash

#
# Copyright (C) 2016 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

test_output=$(net getdomainsid 2>/dev/null)
if [[ $? != 0 ]]; then
    # not joined to a domain, exit now
    exit 0
fi

# Fix duplicate SID for local machine and domain (required for ns6 upgraded systems)
test_count=$(echo "$test_output" | grep -o -E ': S-[0-9-]+' | uniq | wc -l)
if [[ "${test_count}" == "1" ]]; then
    netbiosName=$(testparm -s --parameter-name='netbios name' 2>/dev/null)
    if [[ -n "${netbiosName}" ]]; then
        tdbtool /var/lib/samba/private/secrets.tdb delete "SECRETS/SID/${netbiosName}"
        echo "[NOTICE] generating a new SID for ${netbiosName}..."
        net getlocalsid
    else
        echo "[ERROR] failed to retrieve the machine NetBIOS name. SID not fixed!"
        exit 1
    fi
fi
